version: "3.9"
services:
  api:
    build: .
    image: ${DOCKERHUB_USERNAME:-youruser}/elevate-pro-cicd:${TAG:-dev}
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    healthcheck:
      test: ["CMD", "python", "-c", "import sys,urllib.request; sys.exit(0 if urllib.request.urlopen('http://localhost:8080/health').status==200 else 1)"]
      interval: 30s
      timeout: 3s
      retries: 5
