name: Release
on:
  push:
    tags:
      - 'v*.*.*'
permissions:
  id-token: write   # for keyless signing (Sigstore)
  contents: read
  packages: write
jobs:
  build-push-sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version
        id: meta
        run: echo "version=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Build & Push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/elevate-pro-cicd:${{ steps.meta.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/elevate-pro-cicd:latest

      - name: Generate SBOM (Syft)
        uses: anchore/sbom-action@v0
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/elevate-pro-cicd:${{ steps.meta.outputs.version }}
          artifact-name: sbom-${{ steps.meta.outputs.version }}.spdx.json

      - name: Vulnerability Scan (Trivy)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/elevate-pro-cicd:${{ steps.meta.outputs.version }}
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0

      - name: Sign image (keyless)
        env:
          COSIGN_EXPERIMENTAL: ${{ secrets.COSIGN_EXPERIMENTAL }}
        run: |
          cosign sign --yes ${{ secrets.DOCKERHUB_USERNAME }}/elevate-pro-cicd:${{ steps.meta.outputs.version }}
          cosign sign --yes ${{ secrets.DOCKERHUB_USERNAME }}/elevate-pro-cicd:latest
